[package]
name = "space-invaders"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crossterm = "0.28.1"
unicode-width = "0.2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
